# Site settings
title: Word Power Made Easy Daily Vocabulary
author:
  name: Pankaj Bhatt
  email: pkj.bhatt@yahoo.com
description: "Consistency is the key to success"

# Build settings
remote_theme: jekyll/minima
